---
- name: Check if nvm is installed.
  stat:
    path: ~/.config/nvm
  register: nvm_installed

- name: load nvm installer
  uri:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh
    return_content: yes
  register: nvm_installer
  when: not nvm_installed.stat.exists

- name: run nvm installer
  command:
    argv:
      - "bash"
      - "-c"
      - "{{ nvm_installer.content }}"
  when: not nvm_installed.stat.exists

- name: Ensure ZSH config for nvm is loaded
  copy:
    src: files/config/zsh/zshrc.d/nvm.zsh
    dest: ~/.config/zsh/zshrc.d/nvm.zsh

- name: run nvm node installation
  shell: |
    source ~/.config/nvm/nvm.sh
    nvm install {{ node_version }}
    nvm use node
  args:
    executable: /bin/bash
  when: not nvm_installed.stat.exists
