---
- name: Converge
  hosts: all
  environment:
    XDG_CONFIG_HOME: ~/.config
    XDG_CACHE_HOME: ~/.cache
    XDG_DATA_HOME: ~/.local/share
    ZDOTDIR: ~/.config/zsh

  tasks:
    - name: print out os family
      debug: msg={{ ansible_os_family }}
    - name: Include ansible-role-nodejs
      include_role:
        name: ansible-role-nodejs
