---
- name: Converge
  hosts: all
  environment:
    XDG_CONFIG_HOME: ~{ user }/.config
    XDG_CACHE_HOME: ~{ user }/.cache
    XDG_DATA_HOME: ~{ user }/.local/share
    ZDOTDIR: ~{ user }/.config/zsh

  tasks:
    - name: print out os family
      debug: msg={{ ansible_os_family }}
    - name: Include ansible-role-nodejs
      include_role:
        name: ansible-role-nodejs
