---
- name: Converge
  hosts: all
  environment:
    XDG_CONFIG_HOME: /root/.config
    XDG_CACHE_HOME: /root/.cache
    XDG_DATA_HOME: /root/.local/share
    ZDOTDIR: /root/.config/zsh

  tasks:
    - name: print out os family
      debug: msg={{ ansible_os_family }}
    - name: Include ansible-role-nodejs
      include_role:
        name: ansible-role-nodejs
