---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    user: root
    nvm_version: 'v0.39.1'
    node_version: 'v16.13.2'
  tasks:
  - name: Stat ~{{ user }}/.config/nvm/nvm-exec
    stat:
      path: ~{{ user }}/.config/nvm/nvm-exec
    register: nvm_exists

  - name: Assert ~{{ user }}/.config/nvm/nvm-exec
    assert:
      that: nvm_exists.stat.exists

  - name: Stat ~{{ user }}/.config/nvm/versions/node/{{ node_version }}/bin/node
    stat:
      path: ~{{ user }}/.config/nvm/versions/node/{{ node_version }}/bin/node
    register: node_exists

  - name: Assert ~{{ user }}/.config/nvm/versions/node/{{ node_version }}/bin/node exists
    assert:
      that: node_exists.stat.exists
